# Generated by Django 5.2.3 on 2026-06-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0006_mercadopago_oauth_fields'),
        ('billing', '0010_mercadopagooauthstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision_calculada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_periods', to='SIM_Control.distribuidor')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_commission_periods', to=settings.AUTH_USER_MODEL)),
                ('revendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_periods', to='SIM_Control.revendedor')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month', 'status'], name='billing_com_year_0d192b_idx'), models.Index(fields=['distribuidor', 'year', 'month'], name='billing_com_distrib_c298f2_idx'), models.Index(fields=['revendedor', 'year', 'month'], name='billing_com_revende_e6bb42_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('distribuidor__isnull', False), ('revendedor__isnull', True)), models.Q(('distribuidor__isnull', True), ('revendedor__isnull', False)), _connector='OR'), name='commission_period_exactly_one_seller'), models.UniqueConstraint(condition=models.Q(('distribuidor__isnull', False)), fields=('distribuidor', 'year', 'month'), name='uq_commission_distribuidor_period'), models.UniqueConstraint(condition=models.Q(('revendedor__isnull', False)), fields=('revendedor', 'year', 'month'), name='uq_commission_revendedor_period')],
            },
        ),
    ]
