# Generated by Django 5.2.3 on 2026-06-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_commissionperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionperiod',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commissionperiod',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commissionperiod',
            name='mp_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
