# Generated by Django 5.2.3 on 2026-06-16 20:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0006_mercadopago_oauth_fields'),
        ('billing', '0012_commissionperiod_mp_payment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionperiod',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('blocked', 'Blocked'), ('exempt', 'Exempt')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CommissionExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('start_month', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('end_month', models.PositiveSmallIntegerField()),
                ('months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_exemptions', to=settings.AUTH_USER_MODEL)),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_exemptions', to='SIM_Control.distribuidor')),
                ('revendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_exemptions', to='SIM_Control.revendedor')),
            ],
            options={
                'ordering': ['-start_year', '-start_month'],
                'indexes': [models.Index(fields=['start_year', 'start_month', 'end_year', 'end_month', 'is_active'], name='billing_com_start_y_94c2ee_idx'), models.Index(fields=['distribuidor', 'is_active'], name='billing_com_distrib_0fc0f9_idx'), models.Index(fields=['revendedor', 'is_active'], name='billing_com_revende_dfb1e1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('distribuidor__isnull', False), ('revendedor__isnull', True)), models.Q(('distribuidor__isnull', True), ('revendedor__isnull', False)), _connector='OR'), name='commission_exemption_exactly_one_seller')],
            },
        ),
    ]
