# Generated by Django 5.2.3 on 2025-07-05 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMAssignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=50, unique=True)),
                ('assigned_to_distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribuidor', to='SIM_Control.distribuidor')),
                ('assigned_to_instalador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instalador', to='SIM_Control.distribuidor')),
                ('assigned_to_usuario_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_final', to='SIM_Control.distribuidor')),
            ],
        ),
    ]
