# Generated by Django 5.2.3 on 2025-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0002_simassignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('operator_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('rat_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ue_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
