# Generated by Django 5.2.3 on 2025-07-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0003_simstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simstatus',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
