# Generated by Django 5.2.3 on 2026-02-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0003_integrationlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integrationlog',
            new_name='SIM_Control_logger__31705d_idx',
            old_name='SIM_Control_logger__e4f261_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationlog',
            new_name='SIM_Control_level_ea14f6_idx',
            old_name='SIM_Control_level_651f3b_idx',
        ),
    ]
