# Generated by Django 5.2.3 on 2025-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0006_alter_simquota_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simquota',
            name='threshold_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
