# Generated by Django 5.2.3 on 2025-07-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0008_alter_simquota_last_status_change_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instalador',
            new_name='Revendedor',
        ),
        migrations.RenameField(
            model_name='usuariofinal',
            old_name='instalador',
            new_name='Revendedor',
        ),
        migrations.RemoveField(
            model_name='simassignation',
            name='assigned_to_instalador',
        ),
        migrations.AddField(
            model_name='simassignation',
            name='assigned_to_revendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instalador', to='SIM_Control.revendedor'),
        ),
        migrations.AlterField(
            model_name='simassignation',
            name='assigned_to_usuario_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_final', to='SIM_Control.usuariofinal'),
        ),
    ]
