# Generated by Django 5.2.3 on 2025-07-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0009_rename_instalador_revendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simassignation',
            name='assigned_to_revendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revendedor', to='SIM_Control.revendedor'),
        ),
    ]
