# Generated by Django 5.2.3 on 2025-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0010_alter_simassignation_assigned_to_revendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMSMSQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20, unique=True)),
                ('volume', models.FloatField()),
                ('total_volume', models.FloatField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('peak_throughput', models.IntegerField()),
                ('last_volume_added', models.FloatField()),
                ('last_status_change_date', models.DateTimeField(blank=True, null=True)),
                ('threshold_percentage', models.IntegerField()),
            ],
        ),
    ]
