# Generated by Django 5.2.3 on 2025-07-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0012_vehicle_rename_revendedor_usuariofinal_revendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='SIM_Control.usuariofinal'),
            preserve_default=False,
        ),
    ]
