# Generated by Django 5.2.3 on 2025-07-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0014_alter_revendedor_distribuidor_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofinal',
            name='distribuidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_finales', to='SIM_Control.distribuidor'),
        ),
    ]
