# Generated by Django 5.2.3 on 2025-07-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0015_usuariofinal_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simassignation',
            name='assigned_to_vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='SIM_Control.vehicle'),
        ),
    ]
