# Generated by Django 5.2.3 on 2025-07-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0017_alter_simassignation_assigned_to_distribuidor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=32)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('source_address', models.CharField(max_length=32)),
                ('msisdn', models.CharField(max_length=32)),
                ('udh', models.TextField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('status_id', models.PositiveIntegerField()),
                ('status_description', models.CharField(max_length=128)),
                ('sms_type_id', models.PositiveIntegerField()),
                ('sms_type_description', models.CharField(max_length=128)),
                ('source_address_type_id', models.PositiveIntegerField()),
                ('source_address_type_description', models.CharField(max_length=128)),
            ],
        ),
    ]
