# Generated by Django 5.2.3 on 2025-07-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0018_smsmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='status_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
