# Generated by Django 5.2.3 on 2025-07-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0019_alter_smsmessage_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='msisdn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='retry_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='sms_type_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='sms_type_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='source_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='source_address_type_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='source_address_type_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='status_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
