# Generated by Django 5.2.3 on 2025-07-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0020_alter_smsmessage_msisdn_alter_smsmessage_retry_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='iccid',
        ),
    ]
