# Generated by Django 5.2.3 on 2025-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0021_remove_vehicle_iccid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
