# Generated by Django 5.2.3 on 2025-07-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0022_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simassignation',
            name='iccid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iccid_key', to='SIM_Control.simcard'),
        ),
    ]
