# Generated by Django 5.2.3 on 2025-07-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0023_alter_simassignation_iccid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariofinal',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariofinal',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
