# Generated by Django 5.2.3 on 2025-07-24 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0024_alter_distribuidor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.IntegerField(blank=True, default=0, null=True)),
                ('longitude', models.IntegerField(blank=True, default=0, null=True)),
                ('iccid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='SIM_Control.simcard')),
            ],
        ),
    ]
