# Generated by Django 5.2.3 on 2025-07-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0025_simlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simlocation',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='simlocation',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
