# Generated by Django 5.2.3 on 2025-07-25 02:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0026_alter_simlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simassignation',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simassignation',
            name='last_topup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simassignation',
            name='topup_duration',
            field=models.CharField(blank=True, choices=[('1M', '1 mes'), ('3M', '3 meses'), ('6M', '6 meses'), ('1Y', '1 año'), ('2Y', '2 años')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DISABLE', 'Disable'), ('ASSIGN', 'Assign'), ('REFRESH', 'Refresh'), ('TOPUP', 'Topup'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 7, 25, 2, 41, 15, 898023, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
