# Generated by Django 5.2.3 on 2025-07-25 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0027_simassignation_deactivation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ENABLE', 'Enable'), ('DISABLE', 'Disable'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('REFRESH', 'Refresh'), ('TOPUP', 'Topup'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 2, 44, 39, 939063, tzinfo=datetime.timezone.utc)),
        ),
    ]
