# Generated by Django 5.2.3 on 2025-07-25 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0028_alter_useractionlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ENABLE', 'Enable'), ('DISABLE', 'Disable'), ('SEND_SMS', 'Send SMS'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('REFRESH', 'Refresh'), ('TOPUP', 'Topup'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 3, 49, 1, 401956, tzinfo=datetime.timezone.utc)),
        ),
    ]
