# Generated by Django 5.2.3 on 2025-07-25 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0029_alter_useractionlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 4, 21, 4, 921261, tzinfo=datetime.timezone.utc)),
        ),
    ]
