# Generated by Django 5.2.3 on 2025-07-25 19:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0030_alter_useractionlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 19, 17, 59, 961738, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='SIM_Control.usuariofinal'),
        ),
    ]
