# Generated by Django 5.2.3 on 2025-07-25 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0032_vehicle_sim_alter_useractionlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 19, 49, 25, 137667, tzinfo=datetime.timezone.utc)),
        ),
    ]
