# Generated by Django 5.2.3 on 2025-07-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0033_alter_useractionlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
