# Generated by Django 5.2.3 on 2025-07-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0035_remove_simassignation_assigned_to_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='simassignation',
            name='assigned_to_vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo', to='SIM_Control.vehicle'),
        ),
    ]
