# Generated by Django 5.2.3 on 2025-07-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0036_simassignation_assigned_to_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
