# Generated by Django 5.2.3 on 2025-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0037_alter_useractionlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_lang',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5),
        ),
    ]
