# Generated by Django 5.2.3 on 2025-08-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0039_alter_user_preferred_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limit', models.IntegerField(default=10)),
                ('mt_limit', models.IntegerField(default=45)),
                ('mo_limit', models.IntegerField(default=30)),
            ],
        ),
    ]
