# Generated by Django 5.2.3 on 2025-09-04 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0040_globallimits'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('rfc', models.CharField(blank=True, max_length=15, null=True)),
                ('street', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SIMSMSQuota',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='simassignation',
            name='assigned_to_usuario_final',
        ),
        migrations.RenameField(
            model_name='simassignation',
            old_name='iccid',
            new_name='sim',
        ),
        migrations.RenameField(
            model_name='simlocation',
            old_name='iccid',
            new_name='sim',
        ),
        migrations.RemoveField(
            model_name='distribuidor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='distribuidor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='distribuidor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='monthlysimusage',
            name='iccid',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='revendedor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='simassignation',
            name='assigned_to_distribuidor',
        ),
        migrations.RemoveField(
            model_name='simassignation',
            name='assigned_to_revendedor',
        ),
        migrations.RemoveField(
            model_name='simassignation',
            name='assigned_to_vehicle',
        ),
        migrations.RemoveField(
            model_name='simquota',
            name='iccid',
        ),
        migrations.RemoveField(
            model_name='simstatus',
            name='iccid',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='iccid',
        ),
        migrations.AddField(
            model_name='monthlysimusage',
            name='sim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usages', to='SIM_Control.simcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simassignation',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simassignation',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simquota',
            name='quota_type',
            field=models.CharField(choices=[('DATA', 'Data'), ('SMS', 'SMS')], default='DATA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simquota',
            name='sim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='SIM_Control.simcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simstatus',
            name='sim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sim_status', to='SIM_Control.simcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='sim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='SIM_Control.simcard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='rfc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='street',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='distribuidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revendedores', to='SIM_Control.distribuidor'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='street',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MATRIZ', 'Matriz'), ('DISTRIBUIDOR', 'Distribuidor'), ('REVENDEDOR', 'Revendedor'), ('CLIENTE', 'Cliente')], default='DISTRIBUIDOR', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='distribuidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='SIM_Control.distribuidor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='revendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='SIM_Control.revendedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='SIM_Control.cliente'),
        ),
        migrations.DeleteModel(
            name='UsuarioFinal',
        ),
    ]
