# Generated by Django 5.2.3 on 2025-09-04 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM_Control', '0041_cliente_delete_simsmsquota_remove_vehicle_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysimusage',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to='SIM_Control.simcard'),
        ),
    ]
